name: "profile-stats"
description: "retrieve github profile stats and save locally to repo for further processing"
branding:
  icon: "bar-chart-2"
  color: "blue"
runs:
  using: "node20"
  main: "./dist/index.js"
