name: GitHub Profile Stats

on:
  push:
    branches:
      - main
  schedule:
    # run everyday at 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Run build
        uses: borales/actions-yarn@v5
        with:
          cmd: build

      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # with:

      - uses: stefanzweifel/git-auto-commit-action@v5
